name: Update formula

on:
  repository_dispatch:
    types: [update-formula]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3.0.0
      - run: |
          ./update-formula.py \
            --version ${{ github.event.client_payload.version }} \
            --linux-sha ${{ github.event.client_payload.linux_sha }} \
            --macos-sha ${{ github.event.client_payload.macos_sha }}
      - run: cat Formula/*

