name: Update formula

on:
  push:
    branches: [feature/*]
  repository_dispatch:
    types: [update-formula]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3.0.0
      - run: ./update-formula.py --version ${{ github.event.client_payload.version }}
